- README.md
The link to the badge was inaccurate
> docs(readme): update go report card badge

- handlers/script.go
- handlers/script_test.go
Reworked script exec to deal with timeout more natively via context which also fixes the data race issue observed via `go test -race`. Additionally, this is handling the capture of exit codes in a cleaner fashion.
Reworked tests slightly to reduce redundancy and added new test cases.
> refactor(exec): fix data race

- core/matcher_test.go
- handlers/http_test.go
- remote/slack/helper.go
> gofmt -s fixes

- README.md
- docker/Dockerfile
- docker/Dockerfile.golang
- docker/Dockerfile.ruby
> update to newer base images for ruby and go

- handlers/script_test.go
- testdata/fail.sh
trying to fix test for behavior on travis
> test(exec): fix stdout before error test

- core/configure.go
- remote/discord/remote.go
- version/version.go
Fix a few issues identified by Go Report Card report
> test(reportcard): fix issues identified in go report card

- .travis.yml
> chore(travis): are you on?

- docker/Dockerfile
- docker/Dockerfile.golang
- docker/Dockerfile.ruby
- docker/hooks/build
- hooks/build
- hooks/env
We have migrated from docker hub builds to docker cloud builds, thus we should be able to utilize the native environment variables talked about in https://docs.docker.com/docker-cloud/builds/advanced/.
Also, note that we had to move the `hooks` directory to be relative to `Dockerfile.<name>`.
> chore(docker): attempt to fix docker env variables and unify exports

- README.md
This is an initial first stab at updating the readme. I'd ideally like to add a gif/video showcasing the ease of use, but that can come later.
> docs(readme): Updating readme with more content

- README.md
- remote/discord/remote.go
> Ensure Discord can properly grab bot name

- docker/hooks/build
> chore(docker): remove quotes for tags

- README.md
> docs(readme): update links to github pages

- .github/CONTRIBUTING.md
fixes #81
main.go is currently under cmd/flottbot. The documentation was pointing to the wrong directory.
> fix the contrib checklist

- core/matcher.go
- core/matcher_test.go
> feat(matcher): allow optional args in rule

- handlers/http.go
- handlers/http_test.go
This PR adds support for API responses of the form `[{"testng": "test"}]`. No changes to function signature as it just returns an interface anyways.
> Support for array of JSON in extractFields

- remote/cli/remote.go
Reduce size of ASCII art in CLI mode.
> style(cli): compacting ascii art

- remote/cli/remote.go
Fixes #17 
Quick change to improve CLI experience.
> fix(cli): remove 'need' to press enter

- config-example/rules/kanye.yml
> adding kanye.rest example rule

- models/rule.go
- utils/access_check.go
- utils/access_check_test.go
Enable user restriction by user_id
> restrict users by id

- core/matcher.go
- core/matcher_test.go
- models/rule.go
fixes: #92
Adds `ignore_threads` property to Rule. If set to true, it will prevent the rule from triggering from a thread. Also, adds a `_is_thread_message` variable that a user can use for custom handling.
> feat: add ability to prevent responding in threads

- .travis.yml
- config-example/rules/golang.yml
- config-example/scripts/main.go
To resolve issue #110, I would like to add an example on how to use Go as an exec action within a rule. I was initially confused how to do this, hopefully this will help others figure it out.
I used the following command to test this example:
`docker run -it --rm --name mybot -v ${pwd}/config-example:/go/config target/flottbot:golang /bin/sh -c "./flottbot"` and then sent the command `goscript` to the bot to receive the response "Hi from Go".
> Add Go script example for #110

- .travis.yml
- cmd/flottbot/main.go
- docker/Dockerfile
- docker/Dockerfile.golang
- docker/Dockerfile.python
- docker/Dockerfile.ruby
- go.mod
- go.sum
- remote/slack/helper.go
- remote/slack/util.go
- update Go to 1.13
- update nlopes/slack to latest
- fix deprecations
> chore: go 1.13; bump slack lib; fix deprecations

- remote/slack/helper.go
Added more user fields for usage in bot from Slack API
> enhancement(slack): add more user fields from slack api

- go.sum
- remote/slack/helper.go
To avoid returning unnecessary information
> fix: don't return input

- .github/workflows/publish_latest.yml
- .github/workflows/release.yml
- .goreleaser.yml
Pipeline with steps using golang container don't have docker available. Adjusted jobs/steps that should fix docker builds.
> ci: fix pipeline

- Makefile
Missing semi caused docker command to think we're passing multiple things to it.
> build: add missing semi in makefile

- README.md
Updates README.md to document the changes to run as the unprivileged flottbot user in the
docker images.
Documents changes in https://github.com/target/flottbot/pull/142
> Document changes to user in docker images

- core/configure.go
- core/outputs.go
- core/remotes.go
- go.mod
- models/bot.go
- remote/telegram/remote.go
added support for telegram as a remote  #109 
> Add telegram support

- remote/discord/helper.go
- remote/discord/remote.go
- remote/slack/helper.go
- remote/telegram/remote.go
Feature:
Make timestamps (`_source.timestamp` and `_source.thread_timestamp`) available
Fix (Discord):
Prevent bot from responding to self 
> feat: make timestamp vars available

- README.md
- Fix broken link in README
- Update README to have correct versions of packages installed in docker images
> docs: update readme to correct version and fix link

- LICENSE
same license but full copy included. noticed it didn't get picked up in the side panel on GitHub otherwise
> chore(license): use full text license

- .github/workflows/codeql-analysis.yml
> chore: add codeql

- core/matcher.go
- core/matcher_test.go
- handlers/http.go
- handlers/http_test.go
- models/action.go
- models/http.go
- remote/discord/remote.go
- utils/json.go
- utils/json_test.go
ran `gofmt -w -r 'interface{} -> any' .`
> refactor: replace interface with any

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/validate.yml
- core/matcher.go
- core/remotes.go
- handlers/script.go
- handlers/script_test.go
- remote/slack/helper.go
change actions to install go on vm instead of using container
> chore(actions): use go.mod to install go in actions

- config-example/bot.yml
- core/configure_test.go
- core/outputs.go
- core/remotes.go
- models/bot.go
- remote/cli/remote.go
- remote/discord/remote.go
- remote/gchat/remote.go
- remote/remote.go
- remote/scheduler/remote.go
- remote/slack/helper.go
- remote/slack/remote.go
- remote/slack/util.go
- remote/telegram/remote.go
- testdata/goodbot.yml
removes currently non-functional code related to interactive components (Slack only)
the functionality will likely get re-added at a later time after further refactoring.
> chore: remove non-functional code

- README.md
updating python version in README since https://github.com/target/flottbot/pull/355 merged in
> docs: update python version in README

- .github/CODEOWNERS
> fix: CODEOWNER update

- remote/gchat/helper.go
see https://github.com/target/flottbot/pull/488#pullrequestreview-1725777807 for discussion on this
> enhance(gchat)!: assign email to unique field

- docker/Dockerfile
- docker/Dockerfile.golang
- docker/Dockerfile.python
- docker/Dockerfile.ruby
* --no-cache parameter position
* consistency in other images from https://github.com/target/flottbot/pull/505
> fix: dockerfile inconsistencies

- remote/slack/helper.go
pulled out function to process message event and utilized the function in both app mention (previously unused) and message event.
in some scenarios, a user may only be able to run with app_mention permission where the bot wouldn't be able to respond.
> enhance(slack): utilize app_mention
