- docker/hooks/build
This change allows us to push multiple tags to https://hub.docker.com/r/target/flottbot without having to repeatedly build the image.
The modified Docker cloud configuration looks like:
This change means that on our next tag event will have the following images pushed:
- golang
- ruby
- latest
- `<tag number>`
- `golang-<tag number>`
- `ruby-<tag number>`
> enable building/pushing multiple image tags per Dockerfile

- README.md
- docker/Dockerfile
- docker/Dockerfile.python
- docker/Dockerfile.ruby
> chore(docker): add dockerfile with python and utilize default cmd

- remote/slack/helper.go
This change no longer means that we will be hardcoding user email to be `@target.com`. This could be considered a breaking change since users will need to update the application scoping to include emails.
> fix(slack): stop hardcoding user email domain

- remote/slack/helper.go
Properly sized version of #75 . We are currently only populating users/groups for RTM-only bots. Unfortunately this will decrease test coverage as none of the `/remote` code has tests at the moment. I have tested the fix in a test Slack workspace. Feel free to validate.
> fix(acl): populate user and group info for events api

- .gitignore
- core/matcher.go
- handlers/script.go
- utils/parse.go
- utils/parse_test.go
This PR fixes a bug in `utils.parse.FindArgs`.   `FindArgs` doesn’t properly handle the case where there is an empty quoted argument, like when a variable is empty.  
For example, our rules file might have a command like this:
```yaml
cmd: '/usr/bin/whatever "${_user.id}" "${_user.email}" "${_user.firstname}" "${_user.lastname}" "${_channel.id}" "${_channel.name}" "${_raw_user_input}"'
```
When someone interacts with the bot in a channel, the generated command looks something like this:
```sh
/usr/bin/whatever "userid" "email@domain" "First" "Last" "channelid" "channelname" "string of words"
```
However, when someone interacts with the bot in the **Apps** section of Slack, there is no channel name, so `${_channel.name}` is empty.  Under those circumstances, the generated command looks …
> Improvements to argument processing

- Gopkg.lock
- Gopkg.toml
- core/outputs.go
- handlers/script.go
- remote/discord/helper.go
- remote/discord/remote.go
- remote/slack/remote.go
This PR adds reaction functionality to the Discord remote. I'll note to fully achieve this functionality I needed to add the initiating message id to the message struct, since Discord doesn't have the similar functionality of https://github.com/target/flottbot/blob/9213a3f74f9d0b80b9cd730258545cd61a12d886/remote/slack/remote.go#L40 to determine the message id.
I also updated dependent packages and update the slack reaction comments.
> feat(discord): add reaction support

- core/matcher.go
- core/matcher_test.go
Clone of #108 w/ fixes
Resolves #107
> Support arg+ syntax for argument capture (w/ fixes)

- config-example/rules/schedule.yml
- go.mod
- go.sum
- handlers/http_test.go
- remote/scheduler/remote.go
Updates cron lib to newest version. This will now support both standard and quartz spec syntax for cron scheduling.
closes #20 
>  feat(scheduler): allow standard and quartz spec 

- docker/Dockerfile
- docker/Dockerfile.golang
- docker/Dockerfile.python
- docker/Dockerfile.ruby
Noticed an issue during the docker image build. Apparently there's a bug with multiple successive COPY statements in Docker that we're affected by, see moby/moby/issues/37965 . Instead of applying known workaround, reverting Dockerfiles back to old setup w/ some tweaks.
> ci: reverting dockerfiles due to docker bug

- remote/slack/util.go
Looks like channel id length has changed in some cases. This change will ease up on the length restriction. Will solve issue with some people seeing `Unable to handle channel: UNKNOWN_*` error messages.
> fix(channel): open up channel length

- .github/workflows/publish_latest.yml
- .github/workflows/release.yml
Tag release failed on docker step. Looks like we forgot to check out the repo.
> ci: fix pipeline

- docker/Dockerfile
- docker/Dockerfile.golang
- docker/Dockerfile.python
- docker/Dockerfile.ruby
Runs flottbot as an unprivileged user rather than root in the docker
images. Adds flottbot as a system user with uid 900 by default but allows
setting those values as env vars and set the image to use that user at
runtime.
It doesn't seem necessary to run flottbot as root and my testing with docker images built in this way hasn't shown any issues. It would seem sensible to limit privilege for a service that's going to be exposed to the net.
Currently the changes create the 'flottbot' user with an arbitrary UID of 900. This is configurable by setting ENV in the the Dockerfile. I'm not totally sure what the best way of deciding what UID to use is, but I guess picking a value and documenting it is probably reasonable - otherwise it's a case of just doing useradd and getting a value that can …
> feat!: run flottbot as unprivileged user in docker

- remote/telegram/remote.go
- remote/telegram/util.go
Add better support for calling upon bot from groups and channels. Also, adds support for using slash commands, ie. you can either do `@botname help` or `/help`. i'm not heavy telegram user - let me know if slash commands are supposed to be used differently.
> fix(telegram): make channel/group mentions work

- remote/scheduler/remote.go
Addresses a regression that prevents the usage of all the supported scheduling formats, such as passing timezone into the schedule (eg. `CRON_TZ=Asia/Tokyo 30 04 * * *`) or predefined schedules (eg. `@every 5m`).
fixes #145 
> fix(cron): schedule accepts supported formats

- models/bot.go
- remote/discord/remote.go
- remote/slack/helper.go
- remote/telegram/remote.go
adds global `respond_to_bot` setting to allow your bot to consider messages originating from other bots for matching. it generally frowned upon to respond to other bots, so `false` is the default. more granular control at a rule level may be introduced later. it looks like this was default behavior for the current Telegram integration.
> feat: respond to bots

- core/configure.go
- core/configure_test.go
- core/matcher.go
- core/outputs.go
- core/prommetric.go
- core/remotes.go
- core/rules.go
- go.mod
- go.sum
- handlers/script.go
- models/bot.go
- remote/cli/remote.go
- remote/discord/helper.go
- remote/discord/remote.go
- remote/scheduler/remote.go
- remote/slack/helper.go
- remote/slack/remote.go
- remote/telegram/remote.go
- utils/access_check.go
- utils/rooms.go
Converting logrus to zerolog in the project, #66.
> refactor(log): convert from logrus to zerolog

- core/matcher.go
- core/matcher_test.go
- models/action.go
- models/rule.go
Per the story, this adds `limit_to_rooms` at a rule level which allows for use cases like having one bot service multiple rooms/channels differently.
Additionally, since the next release will have some breaking stuff already, I decided to _add_ `output_to_rooms` to actions instead of _replacing_ `limit_to_rooms` with it. Planning to remove in following release. Will update the docs to just reference `output_to_rooms` already though.
closes https://github.com/target/flottbot/issues/113
> feat(rule): add limit_to_rooms

- .github/CONTRIBUTING.md
- .github/workflows/publish_latest.yml
- README.md
> ci: use main in action

- Makefile
Previously the attempt at deriving GOPATH in the Makefile validate task
would error out because a shell instruction for the Makefile was
missing. This was probably a just a syntax snafu converting from shell
to Make.
Fixes #198
> fix(makefile): fix up inference of GOPATH in validate task for Makefile

- .vscode/launch.json
- cmd/flottbot/main.go
- core/configure.go
- core/configure_test.go
- core/matcher.go
- core/matcher_test.go
- core/outputs.go
- core/prommetric.go
- core/remotes.go
- core/rules.go
- handlers/http.go
- handlers/http_test.go
- handlers/script.go
- handlers/script_test.go
- models/bot.go
- remote/cli/remote.go
- remote/discord/helper.go
- remote/discord/remote.go
- remote/scheduler/remote.go
- remote/slack/helper.go
- remote/slack/remote.go
- remote/telegram/remote.go
- utils/access_check.go
- utils/is_set.go
- utils/is_set_test.go
- utils/parse.go
- utils/parse_test.go
- utils/path.go
- utils/rooms.go
Set up log globally to avoid passing Bot for just logging. Also includes change that closes https://github.com/target/flottbot/issues/187
Additionally:
- moves Bot constructor into `models/bot.go`
- moves a utility function (`IsSet`) into `utils/`
- injects logger into Slack Socket Mode
> refactor(log): detach logger from Bot

- utils/parse.go
- utils/parse_test.go
closes https://github.com/target/flottbot/issues/80
instead of panic-ing, we log an error and return a no-match,
> fix(matcher): don't panic on unsupported regex

- handlers/http.go
- remote/discord/util.go
- remote/slack/util.go
tiny refactor to use .ReplaceAll
> refactor: use .ReplaceAll

- core/matcher.go
- core/matcher_test.go
This change adds support for regex capture groups as input arguments (closes #10). It does so by taking advantage of [named & numbered capture groups](https://pkg.go.dev/regexp/syntax#:~:text=named%20%26%20numbered%20capturing%20group) in the standard library.
This can be used in both "respond" and "hear" rules. Doing so adds argument support for "hear" rules, discussed in #204.
In the following example, the capture group named `word` is processed as an argument with the same name.
```yaml
name: hear
active: true
hear: /can you say (?P<word>\S+) for me/
format_output: "I can say ${word} for you"
```
See the unit tests for more detailed examples.
> feat: support regex capture groups as arguments

- .golangci.yml
- core/configure.go
- core/matcher.go
- handlers/script.go
- remote/slack/helper.go
fix linting rule and affected comments: see https://github.com/golangci/golangci-lint/pull/3002
> refactor: address nolint feedback

- .github/renovate.json
reduce noise by configuring auto-merge on non major dependency updates. can't take effect until repo settings are updated due to reviewer requirement that's in place.
> enhance(ci): group more types of updates and automerge

- config-example/bot.yml
- core/matcher.go
- models/bot.go
This pull request introduces additional customization for the help text in the bot's core functionality. A new configuration option, `custom_help_text_prefix`, has been added to allow users to set a custom prefix for the default help message without altering the automatic help generation process.
> Enhance Help Text Customization in Core Configuration

- models/bot.go
- remote/gchat/helper.go
- remote/gchat/remote.go
This patch introduces a enhancement to the bot functionality with Google Chat. It has been observed that Google Chat has ceased to provide the `event.Space.Threaded` value, leading to an issue where the bot could not determine whether a message was sent in a thread or directly to the group. As a result, the bot was defaulting to responding only in the group and never in a thread.
To resolve this issue, a new global configuration option,`google_chat_force_reply_to_thread`, has been added to the bot's settings. This boolean setting allows administrators to specify whether the bot should always reply within a thread if available or continue to respond in the group. The new setting ensures that the bot's replies are consistent with the desired conversation flow, enhancing the overall user …
> Add Option to Force Replies in Thread for Google Chat Bot

- helm/flottbot/values.yaml
pin helm chart flottbot image to last release, not latest image as it could be unstable
> chore(ci/helm): pin to release, not latest

- docker/Dockerfile
This PR aims to enhance the scripting capabilities of the Flottbot Docker image by adding `curl` and `jq` utilities.
By including these tools in the Docker image, users will have more flexibility and convenience with basic Flottbot image.
> feat: add curl and jq to Docker image for enhanced scripting capabilities

- Makefile
- config-example/rules/reaction.yaml
- core/matcher.go
- core/matcher_test.go
- models/message.go
- models/rule.go
- remote/slack/helper.go
I worked on a slack chat bot that was based on https://github.com/ArcticSnowman/go-slackbot which I added the ability to respond to emojis (reaction).
So this is my first attempt to add reaction support to this bot framework.  Hope this helps with #45 
> Add ability to respond to a message reaction being added or remove 
